### ISSUE TITLE
Using `Type.resolveClass()` should give clear error message

### ISSUE THREAD

**Issue by jasononeil** [elsassph/haxe-modular#18]
**Update:** 

Using `Type.resolveClass()` with code-splitting is probably a bad idea, and currently fails when haxe-loader calls split.js (see below for stack trace)

Giving a clear error message here noting that `Type.resolveClass` must be avoided when using code-splitting would be better.

If possible, generating the error during the Haxe compile would be preferable to generating an error during the webpack compile, as it would then give you accurate position information so you can pinpoint the error.

---

In the elsassph/webpack-haxe-example.git repo, the build fails if I add one line with a `Type.resolveClass()`:

```
    static public function main() {
        Type.resolveClass('Main'); // This line breaks things
        new Main();
    }
```

The error:

```
/home/jason/workspace/webpack-haxe-example/node_modules/haxe-modular/tool/bin/split.js:645
		defs.push(def);
		    ^

TypeError: Cannot read property 'push' of undefined
    at Parser.append (/home/jason/workspace/webpack-haxe-example/node_modules/haxe-modular/tool/bin/split.js:645:7)
    at Parser.inspectExpression (/home/jason/workspace/webpack-haxe-example/node_modules/haxe-modular/tool/bin/split.js:483:12)
    at Parser.walkDeclarations (/home/jason/workspace/webpack-haxe-example/node_modules/haxe-modular/tool/bin/split.js:438:10)
    at Parser.walkRootFunction (/home/jason/workspace/webpack-haxe-example/node_modules/haxe-modular/tool/bin/split.js:424:9)
    at Parser.walkRootExpression (/home/jason/workspace/webpack-haxe-example/node_modules/haxe-modular/tool/bin/split.js:414:9)
    at Parser.walkProgram (/home/jason/workspace/webpack-haxe-example/node_modules/haxe-modular/tool/bin/split.js:405:10)
    at Parser.processInput (/home/jason/workspace/webpack-haxe-example/node_modules/haxe-modular/tool/bin/split.js:334:8)
    at Parser (/home/jason/workspace/webpack-haxe-example/node_modules/haxe-modular/tool/bin/split.js:323:7)
    at Object.Main.run (/home/jason/workspace/webpack-haxe-example/node_modules/haxe-modular/tool/bin/split.js:305:15)
    at processOutput (/home/jason/workspace/webpack-haxe-example/node_modules/haxe-loader/index.js:68:27)
    at exec (/home/jason/workspace/webpack-haxe-example/node_modules/haxe-loader/index.js:46:27)
    at ChildProcess.exithandler (child_process.js:202:7)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:501:12)
error Command failed with exit code 1.
```

I only just found the error, have not investigated why it's happening yet :)

**Comment by jasononeil** [comment]
Derp... it just occurred to me that `Type.resolveClass()` would make it really really hard to support code splitting.  (Unless there's a trick to it I'm missing?)

I'm going to update the issue title to reflect that a better error message is probably what I'm after.

**Comment by elsassph** [comment]
I need to look into that - I never use `Type.resolveClass` so it didn't occur to me...

**Comment by elsassph** [comment]
Gotcha, `Type.resolveClass` emits declarations like: 
```javascript
$hxClasses["haxe.ds.StringMap"] = haxe_ds_StringMap;
```
The parser crashes on that.

**Comment by elsassph** [comment]
Ugh, I think modular needs to be cleaned up - and simplified in fact.

**Comment by elsassph** [comment]
I pushed a minimal fix in the webpack branch - but I've found some issues in code splitting around `ArrayBuffer/Uint8Array` (`haxe.io.Bytes`). I'm doing some additional refactoring.

**Comment by elsassph** [comment]
To confirm: this was a fixable bug - a more consistent refactoring however has been created, see PR #19
